name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pipsalabim'
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            toxenv: "py38"
          - python-version: "3.9"
            toxenv: "py39"
          - python-version: "3.10"
            toxenv: "py310"
          - python-version: "3.11.0-alpha.5"
            toxenv: "py311"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Measuring coverage
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tox -e ${TOXENV}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-py${{ matrix.python-version }}
          path-to-lcov: ./.lcov
          parallel: true
      - name: Functional test
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          if [ "${TOXENV}" == "py311" ]; then
            PYTHON_VERSION="3.11"
          fi
          docker run -v ${PWD}:${PWD} -w ${PWD} \
              dockershelf/python:${PYTHON_VERSION} bash -c \
              "pip install . && \
              python${PYTHON_VERSION} -m pipsalabim.cli update"

  finish:
    name: Finish
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pipsalabim'
    needs: build
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  approve:
    name: Approve pull request
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pipsalabim'
    needs: finish
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v2.2.1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Approve
        uses: hmarr/auto-approve-action@v2.2.1
        if: github.actor == 'LuisAlejandro'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pipsalabim'
    needs: approve
    steps:
      - name: Merge
        uses: actions/github-script@v6
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
      - name: Merge
        uses: actions/github-script@v6
        if: github.actor == 'LuisAlejandro'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
